#pragma config(Sensor, dgtl2,  wheelr,         sensorQuadEncoder)
#pragma config(Sensor, dgtl4,  wheell,         sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  ultrasonic,     sensorSONAR_cm)
#pragma config(Motor,  port2,           right1,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           right2,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           left1,         tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           left2,         tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           lift1,         tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           lift2,         tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port8,           claw,          tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!
// this is the code for the compitition robot --Adam C.


void pre_auton()
{
	int autoforwardvalue;
}

task autonomous()
{
	// forward
	while(true)
	{
		int autoforwardvalue;
		autoforwardvalue = 127;
		// foward
		top:
		motor[right1] = (autoforwardvalue);
		motor[right2] = autoforwardvalue;
		motor[left1] = autoforwardvalue;
		motor[left2] = autoforwardvalue;
	}
	wait1Msec(50);
	if(SensorValue(wheelr) <= 60 && SensorValue(wheell) <= 60){
		goto grab_cube;
	}
grab_cube:
	// grab cube
	//turn 180
	// back
autoforwardvalue = -127;
goto top;
	// put cube on small post

	// AutonomousCodePlaceholderForTesting();  // Remove this function call once you have "real" code.
}


task usercontrol()
{
	// this is the user controled code the right joystick is the drive control
	// the left joystick (up and down) is the lift control
	// 5U and 5D are the claw control
	// -- Adam C.
	while (true)
	{
		motor[right1] = vexRT[Ch1] - vexRT[Ch2];
		motor[right2] = vexRT[Ch1] - vexRT[Ch2];

		motor[left1] = vexRT[Ch1] + vexrt[Ch2];
		motor[left2] = vexRT[Ch1] + vexrt[Ch2];

		motor[lift1] = vexRT[Ch3];
		motor[lift2] = -vexRT[Ch3];

		if( vexRT(Btn5U) == 1 ){
			motor[claw] = 127;
		}
		else if(vexRT(Btn5D) == 1){
			motor[claw] = -127;
		}
		else if(vexRT(Btn5D) == 0 || vexRT(Btn5D) == 0){
			motor[claw] = 0;
		}



		UserControlCodePlaceholderForTesting(); // Remove this function call once you have "real" code.
	}
}
