#pragma config(Sensor, dgtl1,  RightENC,       sensorQuadEncoder)
#pragma config(Sensor, dgtl11, LeftENC,        sensorQuadEncoder)
#pragma config(Motor,  port2,           RightT,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           RightB,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           LeftT,         tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           LeftB,         tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           LiftR1,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           LiftR2,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port8,           LiftL1,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           LiftL2,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port10,          minilift,      tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

int controller = 0;

int base(int r, int l){

	motor(RightT) = r;
	motor(RightB) = -r;

	motor(LeftT) = l;
	motor(LeftB) = l;

	return 0;
}

int lift(int l){
	motor(LiftR1) = -l;
	motor(LiftR2)= -l;

	motor(LiftL1) = l;
	motor(LiftL2) = l;

	return 0;
}

int BaseENC(int t, int p1, int p2)
{
	SensorValue(RightENC) = 0;
	SensorValue(LeftENC) = 0;

	while( abs(SensorValue(RightENC)) <= abs(t) )
	{
		base(p1, p2);
		wait1Msec(20);
		if(abs(SensorValue(LeftENC)) <= abs(t))
		{
			base(0,p2);
		}
	}
	base(0,0);
	wait1Msec(75);
	return 0;
}

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
	// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}


task autonomous()
{
	// .....................................................................................
	// Insert user code here.
	// .....................................................................................

//	AutonomousCodePlaceholderForTesting();  // Remove this function call once you have "real" code.
BaseENC((360 * 9),127,127);

}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{
		while(1 != 0)
		{
			if(controller == 0)
			{
				base( (vexRT(Ch2)), (vexRT(Ch3)) );
			}
			if(controller == 1)
			{
				base( (-vexRT(Ch2)), (-vexRT(Ch3)) );
			}




			if(vexRT(Btn8D) == 1)
			{
				wait1Msec(45*10);
				if(controller == 0)
				{
					controller = 1;
				}
				else if(controller == 1)
				{
					controller = 0;
				}
			}




			if( vexRT(Btn6UXmtr2) == 1)
			{
				lift(127);
			}
			if( vexRT(Btn6DXmtr2) == 1)
			{
				lift(-127);
			}
			else
			{
				lift(0);
			}

			//	( vexRT(Btn6UXmtr2) == 1)? lift(127) : 	( vexRT(Btn6DXmtr2) == 1) ? lift(-127) : lift(0);
		}
	}
}
