#pragma config(Motor,  port1,           right,         tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port4,           clawlift,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           claw,          tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port10,          left,          tmotorVex393HighSpeed, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "RoboLib.h"

task main()
{

forward(3.25);

turn('l', 1);

forward(6.5);

turn('l', 2);

forward(6.5);

turn('l', 1);

backwards(3.25);



}
