#pragma config(Motor,  port1,           right,         tmotorVex393HighSpeed, openLoop, reversed)
#pragma config(Motor,  port2,           right,         tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           left,          tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           left,          tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,            ,             tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "RoboLib.h"

task main()
{

forward(3.25);

turn('l', 1);

forward(6.5);

turn('l', 2);

forward(6.5);

turn('l', 1);

backwards(3.25);



}
