#pragma config(Motor,  port2,           Left,          tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           Right,         tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port10,          light,         tmotorVexFlashlight, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main ()
{

	while(1 == 1)
	{
		if(vexRT(Btn7U) == 1){
			motor(light) = 127;
			wait1Msec(75);
		}

		if(vexRT(Btn7D) == 1){
			motor(light) = 0;
			wait1Msec(75);
		}

		motor[Left]  = vexRT[Ch3];
		motor[Right] = vexRT[Ch2];

	}
}
