#pragma config(Sensor, dgtl11, sonar,          sensorSONAR_cm)
#pragma config(Motor,  port2,           right,         tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           left,          tmotorServoContinuousRotation, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true){
		motor(right) = 127;
		motor(left) = 127;
		wait1Msec(120);

		if(SensorValue[sonar] == 45){

			motor(right) = -127;
			motor(left) = -127;
			wait1Msec(100*4);

			motor(right) = 127;
			motor(left) = -127;
			wait1Msec(100*5);
		}
	}


}
