#pragma config(Motor,  port2,           right1,        tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           right2,        tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port4,           left1,         tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           left2,         tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "motors.h"
task main()
{
while(1==1)
	motors(vexRT(Ch2),vexRT(Ch3));
}
