#pragma config(Sensor, dgtl11, SONAR,          sensorSONAR_cm)
#pragma config(Motor,  port2,           right,         tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           left,          tmotorServoContinuousRotation, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
  int distance_in_cm = 45;   // Create variable 'distance_in_cm' and initialize it to 20(cm).
  while(SensorValue[SONAR] > distance_in_cm)   /* While the Sonar Sensor readings are greater */
  {                                                  /* than the specified, 'distance_in_cm':       */
    motor[right] = 127;                     // Motor B is run at a 75 power level
    motor[left] = 127;                     // Motor C is run at a 75 power level
  }
  motor[right] = 0;
  motor[left] = 0;
}
