#pragma config(Motor,  port2,           right,         tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           left,          tmotorServoContinuousRotation, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
while(vexRT(Btn8U) == 0){
		motor(right) = 127;
		motor(left) = 127;
		wait1Msec(120);

		if(SensorValue(dgtl1) == 0 || SensorValue(dgtl2)  == 0 ){

			motor(right) = -127;
			motor(left) = -127;
			wait1Msec(100*4);

			motor(right) = 127;
			motor(left) = -127;
			wait1Msec(100*5);
		}
		if(SensorValue(dgtl3) == 0){
			motor(right) = -127;
			motor(left) = -127;
			wait1Msec(100*4);

			motor(right) = -127;
			motor(left) = 127;
			wait1Msec(100*5);
		}


	};

}
