#pragma config(Motor,  port1,           one,           tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port10,          ten,           tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
while(true){
	motor(one) = vexRT(Ch2);
	motor(ten) = vexRT(Ch3);
	wait1Msec(50);
}


}
