#pragma config(Motor,  port1,           right,         tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port10,          left,          tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
while(1 != 0)
{
motor(right) = vexRT(Ch2);
motor(left) = vexRT(Ch3);
}
}
