#pragma config(Motor,  port1,           right,         tmotorVex269_HBridge, openLoop)
#pragma config(Motor,  port2,           right,         tmotorServoStandard, openLoop)
#pragma config(Motor,  port9,           left,          tmotorServoStandard, openLoop)
#pragma config(Motor,  port10,          left,          tmotorVex269_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
while(1 != 0)
{
motor(right) = vexRT(Ch2);
motor(left) = vexRT(Ch3);
}
}
