#pragma config(Motor,  port2,           RightT,        tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           RightB,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           LeftT,         tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           LeftB,         tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port6,           LiftR1,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           LiftR2,        tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port8,           LiftL1,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           LiftL2,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port10,          minilift,      tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "lift.h"
#include "base.h"

bool isAutoEnabled = false;

task main()
{
	while(1 != 0)
	{
			base( (vexRT(Ch2)) , (vexRT(Ch3)) );


			// Lift Control Code for the left
			if(vexRT(Btn5U) == 1)
			{
				lift(0,127);
			}
			else if( vexRT(Btn5D) ==1)
			{
				lift(0,-127);
			}
			else
			{
				lift(0,0);
			}


			// Lift control Code for the right
			if(vexRT(Btn6U) == 1)
			{
				lift(127,0);
			}
			else if( vexRT(Btn6D) ==1)
			{
				lift(-127,0);
			}
			else
			{
				lift(0,0);
			}

			//Minilift control code
			if(vexRT(Btn7U) == 1)
			{
				motor(minilift) = 127;
			}
			else if( vexRT(Btn7D) ==1)
			{
				motor(minilift) = -127;
			}
			else
			{
				lift(0,0);
			}
	}
}
