#pragma config(Motor,  port2,           RightT,        tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           RightB,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           LeftT,         tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           LeftB,         tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port6,           LiftR1,        tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port7,           LiftR2,        tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port8,           LiftL1,        tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port9,           LiftL2,        tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port10,          minilift,      tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "RoboMini.h"
task main()
{
while(TRUE)
{

}


}
