#pragma config(Sensor, dgtl2,  wheell,         sensorQuadEncoder)
#pragma config(Sensor, dgtl4,  wheelr,         sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  ultrasonic,     sensorSONAR_cm)
#pragma config(Motor,  port2,           right1,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           right2,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           left1,         tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           left2,         tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           lift1,         tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           lift2,         tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port8,           claw,          tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


#include"RoboHeader.h"

task main()
{
	while(true)
	{
		motors( ( vexRT(Ch2)- vexRT(Ch1) ) ,( vexRT(Ch2) + vexRT(Ch1) ) );

		if(vexRT(Btn5U) == 1 ){
			motor[claw] = 127;
		}
		else if(vexRT(Btn5D) == 1){
			motor[claw] = -127;
		}
		else {
			motor[claw] = 0;
		}
	}
}
