#pragma config(Sensor, dgtl2,  wheell,         sensorQuadEncoder)
#pragma config(Sensor, dgtl4,  wheelr,         sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  ultrasonic,     sensorSONAR_cm)
#pragma config(Motor,  port2,           right1,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           right2,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           left1,         tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           left2,         tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           lift1,         tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           lift2,         tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port8,           claw,          tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!
// this is the code for the compitition robot --Adam C.

#include"RoboHeader.h"

void pre_auton()
{
 bStopTasksBetweenModes = true;
}

task autonomous()
{
	// values
	int exelock = 0;
	int forward = 360*2;
	int timetotop = 200;
	int OETurn = 360*2;
	int clawop = 1*10;

	SensorValue(wheell) = 0;
	SensorValue(Wheelr) = 0;

	while(true)
	{
		// foward
		motors(127, 127);
		while( exelock == 0)
		{
			if(SensorValue(wheell > forward) && SensorValue(wheelr > forward)){
				exelock = 1;
			}
			wait1Msec(75*10);
		}

		// grab cube
		motor(claw) =127;
		wait1Msec(clawop);
		motor(claw) = 0;

		//turn 180
		motors(127, -127);
		while( exelock == 0)
		{
			if(SensorValue(wheell > OETurn) && SensorValue(wheelr > OETurn)){
				exelock = 1;
			}
			wait1Msec(75*10);
		}

		// back
				// foward
		motors(127, 127);
		while( exelock == 0)
		{
			if(SensorValue(wheell > forward) && SensorValue(wheelr > forward)){
				exelock = 1;
			}
			wait1Msec(75*10);
		}

		// put cube on small post
		// turn 90*
		{
			if(SensorValue(wheell > 90) && SensorValue(wheelr > 90)){
				exelock = 1;
			}
			wait1Msec(75*10);
		}
		// Put lift to top
		lift(127);

		wait1Msec(timetotop);
		// move base forward a little than stop base
		motors(127,127);
		wait1Msec(10);
		motors(0,0);
		// open claw
		motor(claw) = -127;
		wait1Msec(clawop);
		motor(claw) = 0;
		// lower lift
		lift(-127);
		wait1Msec(timetotop);
		// AutonomousCodePlaceholderForTesting();  // Remove this function call once you have "real" code.
	}
}


task usercontrol()
{
	// this is the user controled code the right joystick is the drive control
	// the left joystick (up and down) is the lift control
	// 5U and 5D are the claw comotor
	// -- Adam C.
	while (true)
	{
	//	motors(	(vexRT(Ch1) + vexRT[Ch2]) , (vexRT(Ch1) - vexRT[Ch2]));

	motors((vexRT(ch2)),(vexRT(ch3)));
	/*
		motor(right1) = vexRT(Ch2);
		motor(right2) = -vexRT(Ch2);
		motor(left1) = vexRT(Ch3);
		motor(left2) = -vexRT(Ch3);
		*/

		if(vexRT(Btn8D) == 1){

	}

		/*
		// backup code
		motor(lift1) = vexRT(Ch3);
		motor(lift2) = vexRT(Ch3);
		*/

		// Claw control
		if( vexRT(Btn5U) == 1 ){
			motor[claw] = 127;
		}
		else if(vexRT(Btn5D) == 1){
			motor[claw] = -127;
		}
		else if(vexRT(Btn5D) == 0 || vexRT(Btn5D) == 0){
			motor[claw] = 0;
		}
		//				UserControlCodePlaceholderForTesting(); // Remove this function call once you have "real" code.
	}
}
