#pragma config(Sensor, dgtl2,  wheell,         sensorQuadEncoder)
#pragma config(Sensor, dgtl4,  wheelr,         sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  ultrasonic,     sensorSONAR_cm)
#pragma config(Motor,  port2,           right1,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           right2,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           left1,         tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           left2,         tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           lift1,         tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           lift2,         tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port8,           claw,          tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
task main()
{
	while(true)
	{

		// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
		motor(right1) = vexRT(ch2);
		motor(left1)= vexrt(Ch3);

		// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

		if(vexRT(Btn8U) == 1)
		{
			motor(lift1) = 127;
			wait1Msec(10*5);
		}

		if(vexRT(Btn8D) == 1)
		{
			motor(lift1) = -127;
			wait1Msec(10*5);
		}

		else
		{
			motor(lift1) = 0;
			wait1Msec(10*5);
		}



		// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


		if(vexRT(Btn7U) == 1)
		{
			motor(lift2) = 127;
			wait1Msec(10*5);
		}

		if(vexRT(Btn7D) == 1)
		{
			motor(lift2) = -127;
			wait1Msec(10*5);
		}

		else
		{
			motor(lift2) = 0;
			wait1Msec(10*5);
		}


		// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	}

}
