#pragma config(Motor,  port2,           Left,          tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           Right,         tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main ()
{

	while(1 == 1)
	{
		motor[Left]  = vexRT[Ch3];
		motor[Right] = vexRT[Ch2];

	}
}
