#pragma config(Motor,  port2,           RightT,        tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           RightB,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           LeftT,         tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           LeftB,         tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port6,           LiftR1,        tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port7,           LiftR2,        tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port8,           LiftL1,        tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port9,           LiftL2,        tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port10,          minilift,      tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "RoboInclude.c"

// Fuses
bool isEnchoderOnLift = FALSE;
int LiftMotorRevsToTop = 360*5;
int LiftTimeToTop = 50;
int WheelSize = 5;
bool isLiftTop = FALSE;


// Not a Fuse
bool isAutoEnabled = FALSE;

task main()
{
	// Turn me into a compitition template!!!!!!
	while(1 != 0)
	{
		if(isAutoEnabled == FALSE)
		{
			#include "ManualControlCode.c"
			// #include"ManualControlCodeBETA.c"
		}
		if(isAutoEnabled == TRUE)
		{
			#include "AutoCode.c"
		}
	}
}
