#pragma config(Sensor, dgtl2,  wheell,         sensorQuadEncoder)
#pragma config(Sensor, dgtl4,  wheelr,         sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  ultrasonic,     sensorSONAR_cm)
#pragma config(Motor,  port2,           right1,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           right2,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           left1,         tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           left2,         tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           lift1,         tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           lift2,         tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port8,           claw,          tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "RoboHeader.h"

task main()
{
turnbot(360*50, 127, 127);
while(true){
wait10Msec(50);
}
}
