#pragma config(Sensor, dgtl1,  RightENC,       sensorQuadEncoder)
#pragma config(Sensor, dgtl11, LeftENC,        sensorQuadEncoder)
#pragma config(Motor,  port2,           RightT,        tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           RightB,        tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port4,           LeftT,         tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           LeftB,         tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port6,           LiftR1,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           LiftR2,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port8,           LiftL1,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           LiftL2,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port10,          minilift,      tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Base.h"
#include "lift.h"
task main()
{
	while(1 != 0)
	{
		base( (vexRT(Ch2)), (vexRT(Ch3)) );

		if( vexRT(Btn6UXmtr2) == 1)
		{
			lift(127,127);
		}
		if( vexRT(Btn6DXmtr2) == 1)
		{
			lift(-127,-127);
		}
		else
		{
			lift(0,0);
		}
	}
}
